from models import db, Product


def seed_products():
    products = [
        # ─── ELECTRONICS ───────────────────────────────────────────────
        {
            "name": "Sony WH-1000XM5 Wireless Headphones",
            "description": "Industry-leading noise cancellation with 30-hour battery life, multipoint connection, and crystal-clear hands-free calling. Premium audio experience.",
            "price": 24999,
            "original_price": 34990,
            "category": "Electronics",
            "subcategory": "Headphones",
            "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
            "rating": 4.8,
            "review_count": 12453,
            "badge": "Best Seller",
            "is_featured": True,
        },
        {
            "name": "Apple iPad Air 11-inch (M2 Chip)",
            "description": "Supercharged by the M2 chip, with a stunning Liquid Retina display, 12MP front and rear cameras, USB-C connector, and Wi-Fi 6E.",
            "price": 59900,
            "original_price": 64900,
            "category": "Electronics",
            "subcategory": "Tablets",
            "image_url": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&q=80",
            "rating": 4.9,
            "review_count": 8731,
            "badge": "New",
            "is_featured": True,
        },
        {
            "name": "Samsung Galaxy S24 Ultra",
            "description": "200MP camera, S Pen included, Snapdragon 8 Gen 3 processor, 5000mAh battery. The ultimate Galaxy experience.",
            "price": 129999,
            "original_price": 134999,
            "category": "Electronics",
            "subcategory": "Smartphones",
            "image_url": "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&q=80",
            "rating": 4.7,
            "review_count": 5432,
            "badge": "Deal",
            "is_featured": True,
        },
        {
            "name": "LG 4K OLED Smart TV 55-inch",
            "description": "Self-lit OLED pixels, α9 AI Processor 4K Gen6, Dolby Vision IQ, webOS 24. Perfect blacks and infinite contrast.",
            "price": 89999,
            "original_price": 119999,
            "category": "Electronics",
            "subcategory": "TVs",
            "image_url": "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=400&q=80",
            "rating": 4.6,
            "review_count": 3217,
            "badge": "25% Off",
            "is_featured": True,
        },
        {
            "name": "Apple MacBook Air M3",
            "description": "Built for Apple Intelligence. Up to 18 hours of battery life, 13.6-inch Liquid Retina display, 8GB RAM, 256GB SSD.",
            "price": 114900,
            "original_price": 119900,
            "category": "Electronics",
            "subcategory": "Laptops",
            "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&q=80",
            "rating": 4.9,
            "review_count": 9876,
            "badge": "Best Seller",
            "is_featured": True,
        },
        {
            "name": "JBL Flip 6 Portable Speaker",
            "description": "Bold JBL Pro sound, IP67 waterproof & dustproof, up to 12 hours playtime. Perfect for outdoor adventures.",
            "price": 9499,
            "original_price": 13999,
            "category": "Electronics",
            "subcategory": "Speakers",
            "image_url": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&q=80",
            "rating": 4.5,
            "review_count": 7654,
            "badge": "32% Off",
            "is_featured": False,
        },
        {
            "name": "Canon EOS R50 Mirrorless Camera",
            "description": "32.5MP APS-C sensor, 4K video, Eye AF, Dual Pixel AF II. Perfect for content creators and photography enthusiasts.",
            "price": 69999,
            "original_price": 79999,
            "category": "Electronics",
            "subcategory": "Cameras",
            "image_url": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&q=80",
            "rating": 4.7,
            "review_count": 2341,
            "badge": "New",
            "is_featured": False,
        },
        {
            "name": "boAt Rockerz 450 Bluetooth Headphones",
            "description": "15 hours playback, 40mm dynamic drivers, padded earcups, foldable design. Top-notch sound at a budget price.",
            "price": 1299,
            "original_price": 3990,
            "category": "Electronics",
            "subcategory": "Headphones",
            "image_url": "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&q=80",
            "rating": 4.2,
            "review_count": 45231,
            "badge": "67% Off",
            "is_featured": False,
        },

        # ─── FASHION ───────────────────────────────────────────────────
        {
            "name": "Men's Premium Slim Fit Polo",
            "description": "100% pima cotton premium polo shirt with moisture-wicking technology. Available in 12 classic colors. Perfect for office and casual wear.",
            "price": 1299,
            "original_price": 2499,
            "category": "Fashion",
            "subcategory": "Men's Clothing",
            "image_url": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80",
            "rating": 4.3,
            "review_count": 18932,
            "badge": "48% Off",
            "is_featured": True,
        },
        {
            "name": "Women's Floral Maxi Dress",
            "description": "Breathable rayon fabric with elegant floral print. Flowing silhouette perfect for summer occasions. Available in sizes XS to 3XL.",
            "price": 1799,
            "original_price": 3499,
            "category": "Fashion",
            "subcategory": "Women's Clothing",
            "image_url": "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&q=80",
            "rating": 4.4,
            "review_count": 9821,
            "badge": "Deal",
            "is_featured": True,
        },
        {
            "name": "Nike Air Max 270 Sneakers",
            "description": "Max Air unit in the heel delivers all-day comfort. Mesh upper for breathability. React foam midsole for lightweight cushioning.",
            "price": 8995,
            "original_price": 10995,
            "category": "Fashion",
            "subcategory": "Footwear",
            "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
            "rating": 4.6,
            "review_count": 14562,
            "badge": "18% Off",
            "is_featured": False,
        },
        {
            "name": "Genuine Leather Wallet for Men",
            "description": "Full-grain leather bifold wallet with RFID blocking. 6 card slots, 2 bill compartments. Ultra slim design at 6mm.",
            "price": 899,
            "original_price": 1999,
            "category": "Fashion",
            "subcategory": "Accessories",
            "image_url": "https://images.unsplash.com/photo-1591561954557-26941169b49e?w=400&q=80",
            "rating": 4.5,
            "review_count": 7234,
            "badge": "55% Off",
            "is_featured": False,
        },
        {
            "name": "Women's Gold-Plated Watch",
            "description": "Elegant quartz movement watch with stainless steel case, mineral glass crystal, water resistant 30m. Gift-ready packaging included.",
            "price": 2499,
            "original_price": 4999,
            "category": "Fashion",
            "subcategory": "Watches",
            "image_url": "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&q=80",
            "rating": 4.3,
            "review_count": 4321,
            "badge": "50% Off",
            "is_featured": False,
        },

        # ─── HOME & KITCHEN ────────────────────────────────────────────
        {
            "name": "Philips Air Fryer HD9252",
            "description": "Rapid Air technology for up to 90% less fat. 4.1L capacity, digital touch interface, 13 preset programs. Dishwasher-safe parts.",
            "price": 6995,
            "original_price": 9999,
            "category": "Home & Kitchen",
            "subcategory": "Appliances",
            "image_url": "https://images.unsplash.com/photo-1648727832756-b6c8b49f10dd?w=400&q=80",
            "rating": 4.5,
            "review_count": 23451,
            "badge": "30% Off",
            "is_featured": True,
        },
        {
            "name": "Instant Pot Duo 7-in-1",
            "description": "Pressure cooker, slow cooker, rice cooker, steamer, saute, yogurt maker, and warmer in one. 6-quart capacity feeds 6+.",
            "price": 6999,
            "original_price": 9999,
            "category": "Home & Kitchen",
            "subcategory": "Appliances",
            "image_url": "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80",
            "rating": 4.7,
            "review_count": 31245,
            "badge": "Best Seller",
            "is_featured": True,
        },
        {
            "name": "Luxury Egyptian Cotton Bedsheet Set",
            "description": "1000 thread count, 100% long-staple Egyptian cotton. Queen size set with 1 flat sheet, 1 fitted sheet, and 2 pillowcases.",
            "price": 3499,
            "original_price": 6999,
            "category": "Home & Kitchen",
            "subcategory": "Bedding",
            "image_url": "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&q=80",
            "rating": 4.6,
            "review_count": 8765,
            "badge": "50% Off",
            "is_featured": False,
        },
        {
            "name": "Dyson V15 Detect Vacuum Cleaner",
            "description": "Laser reveals microscopic dust. LCD screen shows particle count in real time. Up to 60 minutes run time. HEPA filtration.",
            "price": 52900,
            "original_price": 62900,
            "category": "Home & Kitchen",
            "subcategory": "Appliances",
            "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
            "rating": 4.8,
            "review_count": 5678,
            "badge": "New",
            "is_featured": False,
        },
        {
            "name": "Bosch Kitchen Stand Mixer 1000W",
            "description": "1000W motor with 7 speed settings, 5.4L stainless steel bowl, dough hook, whisk, and mixing beater included.",
            "price": 14999,
            "original_price": 22999,
            "category": "Home & Kitchen",
            "subcategory": "Appliances",
            "image_url": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=80",
            "rating": 4.4,
            "review_count": 6543,
            "badge": "35% Off",
            "is_featured": False,
        },
        {
            "name": "Scented Soy Candle Set (6 Pack)",
            "description": "Hand-poured soy wax candles with premium fragrance oils. 40+ hours burn time each. Lavender, vanilla, and sandalwood scents.",
            "price": 1299,
            "original_price": 2499,
            "category": "Home & Kitchen",
            "subcategory": "Decor",
            "image_url": "https://images.unsplash.com/photo-1602874801007-bd458bb1b8b6?w=400&q=80",
            "rating": 4.6,
            "review_count": 9876,
            "badge": "Deal",
            "is_featured": False,
        },

        # ─── BOOKS ─────────────────────────────────────────────────────
        {
            "name": "Atomic Habits by James Clear",
            "description": "The #1 New York Times bestseller. A proven framework for building good habits and breaking bad ones. Over 10 million copies sold worldwide.",
            "price": 399,
            "original_price": 799,
            "category": "Books",
            "subcategory": "Self Help",
            "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80",
            "rating": 4.8,
            "review_count": 87654,
            "badge": "Best Seller",
            "is_featured": True,
        },
        {
            "name": "The Psychology of Money",
            "description": "Morgan Housel's timeless lessons on wealth, greed, and happiness. 19 short stories exploring how people think about money.",
            "price": 349,
            "original_price": 599,
            "category": "Books",
            "subcategory": "Finance",
            "image_url": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&q=80",
            "rating": 4.7,
            "review_count": 54321,
            "badge": "Deal",
            "is_featured": True,
        },
        {
            "name": "Rich Dad Poor Dad",
            "description": "Robert Kiyosaki's financial education classic. Learn the difference between assets and liabilities, and why schools don't teach financial literacy.",
            "price": 299,
            "original_price": 499,
            "category": "Books",
            "subcategory": "Finance",
            "image_url": "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400&q=80",
            "rating": 4.5,
            "review_count": 123456,
            "badge": "Best Seller",
            "is_featured": False,
        },
        {
            "name": "Clean Code by Robert C. Martin",
            "description": "A handbook of agile software craftsmanship. Essential reading for every software developer to write maintainable, readable code.",
            "price": 999,
            "original_price": 1799,
            "category": "Books",
            "subcategory": "Technology",
            "image_url": "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&q=80",
            "rating": 4.6,
            "review_count": 34521,
            "badge": "45% Off",
            "is_featured": False,
        },

        # ─── SPORTS & FITNESS ──────────────────────────────────────────
        {
            "name": "Adjustable Dumbbell Set 5-50 lbs",
            "description": "Replaces 15 sets of weights. Quick dial adjustment system. Ergonomic handle with anti-slip grip. Includes storage tray.",
            "price": 14999,
            "original_price": 24999,
            "category": "Sports",
            "subcategory": "Gym Equipment",
            "image_url": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80",
            "rating": 4.7,
            "review_count": 8765,
            "badge": "40% Off",
            "is_featured": True,
        },
        {
            "name": "Yoga Mat Premium Non-Slip",
            "description": "6mm thick TPE eco-friendly yoga mat. Double-sided non-slip surface. Includes carrying strap. Sweat resistant and easy to clean.",
            "price": 1299,
            "original_price": 2499,
            "category": "Sports",
            "subcategory": "Yoga",
            "image_url": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80",
            "rating": 4.5,
            "review_count": 19873,
            "badge": "Best Seller",
            "is_featured": False,
        },
        {
            "name": "Whey Protein Powder 2kg",
            "description": "25g protein per serving, low in fat and sugar. Chocolate fudge flavor. Supports muscle recovery and lean muscle building.",
            "price": 2799,
            "original_price": 3999,
            "category": "Sports",
            "subcategory": "Nutrition",
            "image_url": "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&q=80",
            "rating": 4.4,
            "review_count": 12543,
            "badge": "Deal",
            "is_featured": False,
        },
        {
            "name": "Fitbit Charge 6 Fitness Tracker",
            "description": "Built-in GPS, 24/7 heart rate, sleep tracking, 7-day battery, Google Maps & Wallet integration. Water-resistant 50m.",
            "price": 14999,
            "original_price": 19999,
            "category": "Sports",
            "subcategory": "Wearables",
            "image_url": "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&q=80",
            "rating": 4.6,
            "review_count": 6543,
            "badge": "25% Off",
            "is_featured": True,
        },

        # ─── BEAUTY & PERSONAL CARE ────────────────────────────────────
        {
            "name": "Minimalist 10% Niacinamide Serum",
            "description": "Controls excess sebum, minimizes pores, reduces dark spots and blemishes. Lightweight formula for all skin types. 30ml.",
            "price": 399,
            "original_price": 699,
            "category": "Beauty",
            "subcategory": "Skincare",
            "image_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80",
            "rating": 4.7,
            "review_count": 45678,
            "badge": "Best Seller",
            "is_featured": True,
        },
        {
            "name": "L'Oreal Paris Telescopic Mascara",
            "description": "Lengthens lashes up to 60%. Precise brush separates and defines. Long-lasting formula. Ophthalmologist tested.",
            "price": 799,
            "original_price": 1099,
            "category": "Beauty",
            "subcategory": "Makeup",
            "image_url": "https://images.unsplash.com/photo-1631214499178-cef2169a5b68?w=400&q=80",
            "rating": 4.4,
            "review_count": 23451,
            "badge": "27% Off",
            "is_featured": False,
        },
        {
            "name": "Dyson Airwrap Complete Hair Styler",
            "description": "Style with air, not extreme heat. Curls, waves, smooth and dry simultaneously. Comes with 8 attachments. Frizz-free results.",
            "price": 44900,
            "original_price": 49900,
            "category": "Beauty",
            "subcategory": "Hair Care",
            "image_url": "https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=400&q=80",
            "rating": 4.8,
            "review_count": 7890,
            "badge": "New",
            "is_featured": True,
        },

        # ─── GROCERIES ─────────────────────────────────────────────────
        {
            "name": "Organic Green Tea (100 Bags)",
            "description": "USDA Certified Organic green tea from Darjeeling. Rich in antioxidants. Individually wrapped bags to preserve freshness.",
            "price": 499,
            "original_price": 799,
            "category": "Groceries",
            "subcategory": "Beverages",
            "image_url": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",
            "rating": 4.5,
            "review_count": 34521,
            "badge": "37% Off",
            "is_featured": False,
        },
        {
            "name": "Mixed Dry Fruits Premium Pack 1kg",
            "description": "Premium blend of cashews, almonds, walnuts, pistachios and raisins. No added preservatives. Air-tight resealable pack.",
            "price": 899,
            "original_price": 1299,
            "category": "Groceries",
            "subcategory": "Snacks",
            "image_url": "https://images.unsplash.com/photo-1611779796886-72d39c9f1e7a?w=400&q=80",
            "rating": 4.6,
            "review_count": 19876,
            "badge": "Deal",
            "is_featured": False,
        },

        # ─── TOYS & GAMES ──────────────────────────────────────────────
        {
            "name": "LEGO Technic Bugatti Bolide",
            "description": "905 pieces, 1:10 scale model with authentic aerodynamic body panels, W16 engine, and movable rear wing. Ages 10+.",
            "price": 8499,
            "original_price": 11999,
            "category": "Toys",
            "subcategory": "LEGO",
            "image_url": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&q=80",
            "rating": 4.8,
            "review_count": 4321,
            "badge": "29% Off",
            "is_featured": True,
        },
        {
            "name": "PlayStation 5 DualSense Controller",
            "description": "Experience haptic feedback and adaptive triggers. Built-in microphone, USB-C charging, 12-hour battery life. Midnight Black edition.",
            "price": 6499,
            "original_price": 6990,
            "category": "Toys",
            "subcategory": "Gaming",
            "image_url": "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&q=80",
            "rating": 4.9,
            "review_count": 15678,
            "badge": "Best Seller",
            "is_featured": True,
        },
    ]

    for p in products:
        product = Product(**p)
        db.session.add(product)

    db.session.commit()
    print(f"Seeded {len(products)} products successfully!")
